// <auto-generated />
using Database.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220110094208_changeDamageType")]
    partial class changeDamageType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Database.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 12,
                            AttackModifier = 3,
                            AttackPerRound = 4,
                            Damage = "1d4",
                            DamageModifier = 2,
                            HitPoints = 40,
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 7,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d4",
                            DamageModifier = 0,
                            HitPoints = 13,
                            Name = "Lemure"
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 17,
                            AttackModifier = 4,
                            AttackPerRound = 2,
                            Damage = "4d8",
                            DamageModifier = 4,
                            HitPoints = 136,
                            Name = "Abbot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
