name: .NET

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  HW1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW1
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW1
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW1
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW1TestCoverageReport.xml

  HW2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW2
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW2
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW2
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW2TestCoverageReport.xml

  HW4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW4
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW4
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW4
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW4TestCoverageReport.xml

  HW5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW5
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW5
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW5
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW5TestCoverageReport.xml

  HW6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW6
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW6
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW6
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW6TestCoverageReport.xml

  HW8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW8
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW8
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW8
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW8TestCoverageReport.xml

  HW9:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW9
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW9
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW9
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW9TestCoverageReport.xml

  HW10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW10
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW10
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW10
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW10TestCoverageReport.xml

  HW11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./HW11
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./HW11
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./HW11
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./.github/workflows/HW11TestCoverageReport.xml
